### ISSUE TITLE
Definir e implementar Banco de Dados

### ISSUE THREAD

**Issue by ederknd** [ederknd/recycleplus#4]
Uma questão q tem ficado em aberto é qual DB vamos escolher, como a @maryana162 já possui mais conhecimento em relação a isso, vou deixar a cargo dela escolher o DB, se vai ser relacional ou não e qual db sera, ex: mongoDB, postgresql , mysql.... e tb implementar o Db em questão no repositorio do projeto.

**Comment by maryana162** [comment]
[recycleplus.zip](https://github.com/ederknd/recycleplus/files/4089154/recycleplus.zip)

**Comment by maryana162** [comment]
ok acho que nao sei postar o negocio

**Comment by maryana162** [comment]
ok acho que n sei postar direito

**Comment by maryana162** [comment]
mas fiz ai, da uma olhada pq fiz bem simples pq nao vamos ter mt informação a armazenar
